version: "3.9"
services:

  db:
    image: postgres
    env_file: ./.env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U $POSTGRES_USER -h db
      interval: 30s
      timeout: 30s

  redis:
    image: "redis:alpine"
    env_file: ./.env
    command: >
      --requirepass $REDIS_PASSWORD
    environment:
     - REDIS_REPLICATION_MODE=master
     - C_FORCE_ROOT=true

  nginx-static:
    image: nginx:latest
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
      - /static:/static
    depends_on:
      - app

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:5000
    volumes:
      - .:/code
      - ./Brotify/static:/static:ro
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - C_FORCE_ROOT=true
    depends_on:
      - db
      - redis
    entrypoint: ./entrypoint.sh