[APP]
frontend_root_url = app.nectar.buzz
debug = true
log_level = DEBUG
log_main_file = ./backend.log
secret_key = cE48SFxv6V8SBuUW3kBLRvu4mzyhnEcG7PTvz59XMN475H6agQmGhdUWa6NuB39p
use_https = false
default_yard_radius_in_meters = 360
default_hht_yard_radius_in_meters = 45
worker_default_password_salt = worker_default_password_salt_placeholder
support_email_address = support@nectar.buzz
gmaps_api_key = AIzaSyD9dmh8V2yFJSpcRs84byzGTL6Ij_K_M9s
fetch_address_from_external_api = false

[DATABASE]
engine = django.contrib.gis.db.backends.postgis
host = localhost
port = 5433
name = apiarydbv3-local
user = conorato
password = 123
# https://docs.djangoproject.com/en/3.0/ref/settings/#conn-max-age
connection_max_age = 0

[SMTP]
backend = django.core.mail.backends.console.EmailBackend
host = host_placeholder
port = port_placeholder
tls = tls_placeholder
user = user_placeholder
password = password_placeholder

[AMQP]
url = amqp://localhost:5672
queue = data_input
messaging_queue = messaging_hub_v3
alerts_queue = alerts
