# Generated by Django 4.0 on 2021-12-30 16:31

from django.db import migrations, models
from django.contrib.auth.models import User
import django.db.models.deletion
import Brotify.config as config


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    def generate_superuser(apps, schema_editor):

        DJANGO_SU_NAME = config.settings['APP']['django_su_name']
        DJANGO_SU_EMAIL = config.settings['APP']['django_su_email']
        DJANGO_SU_PASSWORD = config.settings['APP']['django_su_password']

        superuser = User.objects.create_superuser(
            username=DJANGO_SU_NAME,
            email=DJANGO_SU_EMAIL,
            password=DJANGO_SU_PASSWORD)

        superuser.save()

    operations = [
        migrations.CreateModel(
            name='SocialUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('avatar', models.ImageField(default='default_user_pic.webp', upload_to='profile_pic', verbose_name='Avatar')),
                ('description', models.TextField(blank=True, default='', max_length=2000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.RunPython(generate_superuser),
    ]
