# Generated by Django 3.0.4 on 2020-04-10 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
