# Generated by Django 3.0.4 on 2020-04-11 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200410_1325'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
