# Generated by Django 3.0.4 on 2020-05-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200502_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images_profil', verbose_name='Mon avatar'),
        ),
    ]
