# Generated by Django 3.0.4 on 2020-05-25 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200525_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialuser',
            name='avatar',
        ),
    ]
