# Generated by Django 3.0.4 on 2020-05-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20200525_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Mon avatar'),
        ),
    ]
