# Generated by Django 3.0.6 on 2020-06-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20200608_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='avatar',
            field=models.ImageField(default='default_user_pic.webp', upload_to='profile_pic', verbose_name='Mon avatar'),
        ),
    ]
