# Generated by Django 3.0.6 on 2020-06-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20200608_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='avatar',
            field=models.ImageField(blank=True, default='default_user_pic.webp', null=True, upload_to='profile_pic', verbose_name='Mon avatar'),
        ),
    ]
