# Generated by Django 3.0.6 on 2020-06-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_remove_socialuser_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialuser',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
