# Generated by Django 3.1.7 on 2021-03-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_socialuser_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='avatar',
            field=models.ImageField(blank=True, default='default_user_pic.webp', upload_to='profile_pic', verbose_name='Avatar'),
        ),
    ]
