# Generated by Django 3.1.7 on 2021-03-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20210322_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='avatar',
            field=models.ImageField(blank=True, default='/static/profile_pic/default_user_pic.webp', upload_to='profile_pic', verbose_name='Avatar'),
        ),
    ]
