# Generated by Django 3.1.7 on 2021-03-22 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20210322_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='avatar',
            field=models.ImageField(blank=True, default='default_user_pic.webp', null=True, upload_to='profile_pic', verbose_name='Avatar'),
        ),
    ]
