# Generated by Django 4.0 on 2021-12-30 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('spotify_id', models.CharField(max_length=25, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('spotify_id', models.CharField(max_length=24, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('url_cover_small', models.SlugField(max_length=100)),
                ('url_cover_medium', models.SlugField(max_length=100)),
                ('url_cover_large', models.SlugField(max_length=100)),
                ('url_track', models.SlugField(max_length=100)),
                ('url_player', models.SlugField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LikedTrack',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('user_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.track')),
            ],
        ),
        migrations.CreateModel(
            name='LikedArtist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('liked_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.artist')),
                ('related_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('spotify_id', models.CharField(default='', max_length=25)),
                ('name', models.CharField(default='', max_length=100)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.artist')),
            ],
        ),
    ]
