# Generated by Django 3.0.4 on 2020-05-02 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_artist', models.CharField(default='', max_length=25)),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_track', models.CharField(default='', max_length=25)),
                ('title', models.CharField(default='', max_length=100)),
                ('artist', models.CharField(default='', max_length=100)),
                ('album', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Biblio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('user_songs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_songs', to='biblio.Track')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_album', models.CharField(default='', max_length=25)),
                ('name', models.CharField(default='', max_length=100)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.Artist')),
            ],
        ),
    ]
