# Generated by Django 3.0.4 on 2020-03-29 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Biblio',
        ),
    ]
