# Generated by Django 4.0 on 2022-01-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='track',
            name='url_cover_large',
            field=models.SlugField(max_length=500),
        ),
        migrations.AlterField(
            model_name='track',
            name='url_cover_medium',
            field=models.SlugField(max_length=500),
        ),
        migrations.AlterField(
            model_name='track',
            name='url_cover_small',
            field=models.SlugField(max_length=500),
        ),
        migrations.AlterField(
            model_name='track',
            name='url_player',
            field=models.SlugField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='url_track',
            field=models.SlugField(max_length=500),
        ),
    ]
