# Generated by Django 3.0.4 on 2020-04-27 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0002_auto_20200329_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_album', models.CharField(default='', max_length=25)),
                ('name', models.CharField(default='', max_length=100)),
                ('year', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_artist', models.CharField(default='', max_length=25)),
                ('name', models.CharField(default='', max_length=100)),
                ('genre', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_track', models.CharField(default='', max_length=25)),
                ('title', models.CharField(default='', max_length=100)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.Album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.Artist')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.Artist'),
        ),
    ]
