# Generated by Django 3.0.4 on 2020-05-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0002_delete_biblio'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='url_cover',
            field=models.CharField(default='', max_length=64),
        ),
    ]
