# Generated by Django 3.0.4 on 2020-05-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0003_track_url_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='url_track',
            field=models.CharField(default='', max_length=53),
        ),
        migrations.AlterField(
            model_name='track',
            name='id_track',
            field=models.CharField(default='', max_length=24),
        ),
    ]
