# Generated by Django 3.0.4 on 2020-04-27 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0003_auto_20200426_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='year',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='genre',
        ),
    ]
