# Generated by Django 3.0.4 on 2020-05-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0004_auto_20200503_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='url_cover',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='track',
            name='url_track',
            field=models.CharField(default='', max_length=100),
        ),
    ]
