# Generated by Django 3.0.4 on 2020-05-19 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0006_biblio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Biblio',
        ),
    ]
