# Generated by Django 3.0.4 on 2020-05-19 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0008_biblio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblio',
            name='user_songs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_songs', to='biblio.Track'),
        ),
    ]
