# Generated by Django 3.0.4 on 2020-05-20 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0009_auto_20200519_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biblio',
            name='user_songs',
        ),
        migrations.AddField(
            model_name='biblio',
            name='user_song',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_song', to='biblio.Track'),
        ),
    ]
