# Generated by Django 3.0.4 on 2020-05-20 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0011_auto_20200520_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblio',
            name='user_song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_song', to='biblio.Track'),
        ),
    ]
