# Generated by Django 3.0.4 on 2020-05-20 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0013_auto_20200520_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='track',
            name='id_track',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='track',
            name='url_cover',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='track',
            name='url_track',
            field=models.CharField(max_length=100),
        ),
    ]
