# Generated by Django 3.0.4 on 2020-05-20 23:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0014_auto_20200520_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
