# Generated by Django 3.0.4 on 2020-05-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0015_track_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
