# Generated by Django 3.0.4 on 2020-05-21 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0016_auto_20200520_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='url_cover',
            new_name='url_cover_medium',
        ),
    ]
