# Generated by Django 3.0.4 on 2020-05-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0019_auto_20200521_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='url_cover_large',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='track',
            name='url_cover_medium',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='track',
            name='url_cover_small',
            field=models.CharField(max_length=100),
        ),
    ]
