# Generated by Django 3.0.4 on 2020-05-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0020_auto_20200521_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='url_player',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
