# Generated by Django 3.0.6 on 2020-05-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0022_auto_20200522_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='date_added',
        ),
        migrations.AddField(
            model_name='biblio',
            name='date_added',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
