# Generated by Django 3.0.6 on 2020-05-29 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0023_auto_20200527_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='id_track',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
