# Generated by Django 3.0.6 on 2020-05-29 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0024_auto_20200528_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biblio',
            name='user_song',
        ),
    ]
