# Generated by Django 3.0.6 on 2020-05-29 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0025_remove_biblio_user_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblio',
            name='user_song',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_song', to='biblio.Track'),
            preserve_default=False,
        ),
    ]
