# Generated by Django 3.0.6 on 2020-05-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0026_biblio_user_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='url_cover_large',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='track',
            name='url_cover_medium',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='track',
            name='url_cover_small',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='track',
            name='url_player',
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='url_track',
            field=models.SlugField(max_length=100),
        ),
    ]
