# Generated by Django 3.0.6 on 2020-05-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0027_auto_20200529_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='id_track',
            field=models.CharField(max_length=24),
        ),
    ]
