# Generated by Django 3.0.6 on 2020-05-29 16:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biblio', '0028_auto_20200529_1218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Biblio',
            new_name='LikedTrack',
        ),
    ]
