# Generated by Django 3.0.6 on 2020-05-29 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biblio', '0030_auto_20200529_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedtrack',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='likedtrack',
            name='user_song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.Track'),
        ),
    ]
