# Generated by Django 3.0.6 on 2020-05-30 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0031_auto_20200529_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedtrack',
            name='date_added',
        ),
    ]
