# Generated by Django 3.0.6 on 2020-06-01 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biblio', '0032_remove_likedtrack_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='id_artist',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='LikedArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.Track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
