# Generated by Django 3.0.6 on 2020-06-01 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0033_auto_20200601_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedartist',
            name='liked_artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.Artist'),
        ),
    ]
