# Generated by Django 3.0.6 on 2020-06-02 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0034_auto_20200601_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedtrack',
            name='date_added',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
