# Generated by Django 3.0.6 on 2020-06-02 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0035_likedtrack_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedartist',
            name='related_track',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='biblio.Track'),
            preserve_default=False,
        ),
    ]
